# 목표 : 선형 모델 기반의 분류 모델 구현
- 데이터 : sklearn.datasets의 iris
- 피쳐 : 2개
- 타겟 : 3개

(1) 모듈 로딩 & 데이터 준비

In [63]:
# 모듈 로딩
from sklearn.datasets import load_iris
import pandas as pd
import numpy as np

In [64]:
# 데이터 로딩 => Bunch 타입으로 dict와 유사한 scikit-learn 클래스
dataXy = load_iris(return_X_y=True)
print(type(dataXy), len(dataXy), type(dataXy[0]))

<class 'tuple'> 2 <class 'numpy.ndarray'>


In [65]:
# 데이터와 타겟을 DataFrame 형식으로 로딩
dataXy = load_iris(return_X_y=True, as_frame=True)
print(type(dataXy), len(dataXy), type(dataXy[0]))

<class 'tuple'> 2 <class 'pandas.core.frame.DataFrame'>


In [66]:
data = load_iris()
print(data.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])


In [67]:
# 3가지 품종 피쳐와 타겟
feature = dataXy[0]
target = dataXy[1]

In [68]:
# 2가지 품종 피쳐와 타겟
feature100 = dataXy[0][:100]
target100 = dataXy[1][:100]

In [69]:
feature100.shape, target100.shape

((100, 4), (100,))

(2) 모델 학습 진행

In [70]:
# 모듈 로딩
from sklearn.linear_model import LogisticRegression

In [71]:
# 모델 인스턴스 생성
model = LogisticRegression(max_iter=1000)
model.fit(feature, target)

LogisticRegression(max_iter=1000)

In [72]:
# 학습 후 결정된 모델 파라미터 확인
print('class_ : ', model.classes_)
print('feature_names_in_ : ', model.feature_names_in_)
print('n_iter_ : ', model.n_iter_)
print('coef_ : ', model.coef_)
print('intercept_ : ', model.intercept_)

class_ :  [0 1 2]
feature_names_in_ :  ['sepal length (cm)' 'sepal width (cm)' 'petal length (cm)'
 'petal width (cm)']
n_iter_ :  [120]
coef_ :  [[-0.42364806  0.96739434 -2.51708319 -1.07937296]
 [ 0.53447765 -0.3216458  -0.20639707 -0.94423775]
 [-0.11082959 -0.64574854  2.72348026  2.02361071]]
intercept_ :  [  9.84997373   2.23721656 -12.08719029]


In [73]:
model.score(feature100, target100)

0.97

In [74]:
model.predict(feature.iloc[[0]])

array([0])

In [75]:
model.predict(feature.iloc[[-1]])

array([2])